//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDoGo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebDoGoEntities : DbContext
    {
        public WebDoGoEntities()
            : base("name=WebDoGoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_blog_tra> tbl_blog_tra { get; set; }
        public virtual DbSet<tblSysPicture> tblSysPictures { get; set; }
        public virtual DbSet<web_vangia_category> web_vangia_category { get; set; }
        public virtual DbSet<web_vangia_config> web_vangia_config { get; set; }
        public virtual DbSet<web_vangia_doitac> web_vangia_doitac { get; set; }
        public virtual DbSet<web_vangia_duanmau> web_vangia_duanmau { get; set; }
        public virtual DbSet<web_vangia_employee> web_vangia_employee { get; set; }
        public virtual DbSet<web_vangia_language> web_vangia_language { get; set; }
        public virtual DbSet<web_vangia_menu> web_vangia_menu { get; set; }
        public virtual DbSet<web_vangia_menucon> web_vangia_menucon { get; set; }
        public virtual DbSet<web_vangia_news> web_vangia_news { get; set; }
        public virtual DbSet<web_vangia_products> web_vangia_products { get; set; }
        public virtual DbSet<web_vangia_project> web_vangia_project { get; set; }
        public virtual DbSet<web_vangia_silde> web_vangia_silde { get; set; }
        public virtual DbSet<web_vangia_team> web_vangia_team { get; set; }
        public virtual DbSet<web_vangia_tuyendung> web_vangia_tuyendung { get; set; }
        public virtual DbSet<web_vangia_type_products> web_vangia_type_products { get; set; }
        public virtual DbSet<web_vangia_typeproject> web_vangia_typeproject { get; set; }
    }
}
