//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDoGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_vangia_category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Order_tt { get; set; }
        public string Description { get; set; }
        public string IconClass { get; set; }
        public Nullable<int> IdCompany { get; set; }
    }
}
