//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiManga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdvertGift
    {
        public int IdAdvertGift { get; set; }
        public string NameAdvertGift { get; set; }
        public string DescriptionAdvertGift { get; set; }
        public Nullable<int> IdTypeAdvertGift { get; set; }
        public Nullable<int> IdCategoryAdvertGift { get; set; }
        public Nullable<int> IdCityAdvertGift { get; set; }
        public Nullable<int> StatusAdvertGift { get; set; }
        public Nullable<System.DateTime> CreatedDateAdvertGift { get; set; }
        public string KeySearchAdvertGift { get; set; }
        public string ShortDesAdvertGift { get; set; }
        public string ImgAdvertGift { get; set; }
        public string MusicAdvertGift { get; set; }
    }
}
