//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiManga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdvertManga
    {
        public int IdAdvertManga { get; set; }
        public string NameAdvertManga { get; set; }
        public string CodeAdvertManga { get; set; }
        public string DesAdvertManga { get; set; }
        public string NameAuthorAdvertManga { get; set; }
        public Nullable<int> StatusAdvertManga { get; set; }
        public Nullable<int> StatusChapAdvertManga { get; set; }
        public Nullable<int> CountChapAdvertManga { get; set; }
        public string TypeAdvertManga { get; set; }
        public string ImgAdvertManga { get; set; }
    }
}
