//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiManga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCityGift
    {
        public int IdCityGift { get; set; }
        public string NameCityGift { get; set; }
        public Nullable<int> StatusCityGift { get; set; }
        public string CodeCityGift { get; set; }
        public Nullable<decimal> LatitudeGift { get; set; }
        public Nullable<decimal> LongitudeGift { get; set; }
    }
}
