//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiManga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChapterManga
    {
        public int IdChapterManga { get; set; }
        public string NameChapterManga { get; set; }
        public Nullable<int> StatusChapterManga { get; set; }
        public Nullable<int> IdAdvertManga { get; set; }
    }
}
