//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiManga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDoge
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Status { get; set; }
        public string Money { get; set; }
        public string Pass { get; set; }
        public string CreateDate { get; set; }
        public string ipServer { get; set; }
        public Nullable<int> statusEnd { get; set; }
        public Nullable<int> statusStart { get; set; }
    }
}
