//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiManga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeviceManga
    {
        public int IdDevice { get; set; }
        public string SerialDevice { get; set; }
        public string ModelDevice { get; set; }
        public string ProductDevice { get; set; }
        public string ImeiDevice { get; set; }
        public string OsVersionDevice { get; set; }
        public Nullable<int> OSApiLevelDevice { get; set; }
        public string OsDevice { get; set; }
    }
}
