//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public int IdCategory { get; set; }
        public string NameCategory { get; set; }
        public Nullable<int> StatusCategory { get; set; }
        public string NameCategory_en { get; set; }
        public Nullable<int> IdCompany { get; set; }
    }
}
