//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTypeGift
    {
        public int IdTypeGift { get; set; }
        public string NameTypeGift { get; set; }
        public string DescriptionTypeGift { get; set; }
        public Nullable<int> StatusTypeGift { get; set; }
        public Nullable<int> OrderTypeGift { get; set; }
        public Nullable<int> IdTypeCity { get; set; }
    }
}
