//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APImyPromotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_advert_promotion
    {
        public int advert_id { get; set; }
        public string advert_name { get; set; }
        public Nullable<int> advert_status { get; set; }
        public string advert_description { get; set; }
        public Nullable<System.DateTime> advert_posted_date { get; set; }
        public Nullable<System.DateTime> advert_modifi_date { get; set; }
        public Nullable<System.DateTime> advert_created_date { get; set; }
        public Nullable<System.DateTime> advert_expires_date { get; set; }
        public string advert_street { get; set; }
        public Nullable<int> advert_state_id { get; set; }
        public Nullable<int> advert_district_id { get; set; }
        public Nullable<int> advert_ward_id { get; set; }
        public Nullable<int> advert_category_id { get; set; }
        public Nullable<double> advert_price { get; set; }
    }
}
