//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APImyPromotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_promotion
    {
        public int id_user_promotion { get; set; }
        public string name_user_promotion { get; set; }
        public string email_user_promotion { get; set; }
        public string phone_user_promotion { get; set; }
        public string first_name_user_promotion { get; set; }
        public string last_name_user_promotion { get; set; }
        public Nullable<int> type_role_user_promotion { get; set; }
        public Nullable<int> status_user_promotion { get; set; }
        public string pass_user_promotion { get; set; }
    }
}
