//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APImyPromotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brand_promotion
    {
        public int id_brand_promotiom { get; set; }
        public string name_brand_promotiom { get; set; }
        public string address_brand_promotiom { get; set; }
        public Nullable<int> percent_brand_promotiom { get; set; }
        public Nullable<int> status_brand_promotiom { get; set; }
        public Nullable<int> type_brand_promotiom { get; set; }
        public string phone_brand_promotiom { get; set; }
        public string working_brand_promotiom { get; set; }
        public Nullable<int> advert_id_brand_promotiom { get; set; }
        public string img_brand_promotiom { get; set; }
    }
}
