//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISendGift.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryGift
    {
        public int IdCategoryGift { get; set; }
        public string NameCategoryGift { get; set; }
        public Nullable<int> StatusCategoryGift { get; set; }
        public Nullable<int> IdCategoryCityGift { get; set; }
    }
}
