//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description_service
    {
        public int id { get; set; }
        public string MaDV { get; set; }
        public string TenDV { get; set; }
        public string SOKHOITAO { get; set; }
        public string SOTHUTU { get; set; }
        public string SOPHUCVU { get; set; }
        public Nullable<bool> Cam { get; set; }
        public string TOMTAT { get; set; }
        public string Service { get; set; }
        public string Giave { get; set; }
    }
}
