//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMTUYEN
    {
        public string IDTUYEN { get; set; }
        public string MATUYEN { get; set; }
        public string TENTUYENENG { get; set; }
        public string TENTUYENVN { get; set; }
        public string MATRAMDAU { get; set; }
        public string MATRAMGIUA { get; set; }
        public string MATRAMCUOI { get; set; }
        public string TONGTRAM { get; set; }
        public Nullable<int> MUCDO { get; set; }
        public Nullable<System.DateTime> THOIGIANTOANTRAM { get; set; }
        public Nullable<int> GIAVE1 { get; set; }
        public string DIENGIAIVE1 { get; set; }
        public Nullable<bool> CAMVE1 { get; set; }
        public string IDVE1IDHOADON { get; set; }
        public Nullable<int> GIAVE2 { get; set; }
        public string DIENGIAIVE2 { get; set; }
        public Nullable<bool> CAMVE2 { get; set; }
        public string IDVE2IDHOADON { get; set; }
        public Nullable<int> GIAVE3 { get; set; }
        public string DIENGIAIVE3 { get; set; }
        public Nullable<bool> CAMVE3 { get; set; }
        public string IDVE3IDHOADON { get; set; }
        public Nullable<int> GIAVE4 { get; set; }
        public string DIENGIAIVE4 { get; set; }
        public Nullable<bool> CAMVE4 { get; set; }
        public string IDVE4IDHOADON { get; set; }
        public Nullable<int> GIAVE5 { get; set; }
        public string DIENGIAIVE5 { get; set; }
        public Nullable<bool> CAMVE5 { get; set; }
        public string IDVE5IDHOADON { get; set; }
        public Nullable<int> GIAVE6 { get; set; }
        public string DIENGIAIVE6 { get; set; }
        public Nullable<bool> CAMVE6 { get; set; }
        public string IDVE6IDHOADON { get; set; }
    }
}
