//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMTUYENCHITIETTRAM
    {
        public int ID { get; set; }
        public string IDTUYEN { get; set; }
        public string MATRAM { get; set; }
        public Nullable<bool> TRAMDAU { get; set; }
        public Nullable<bool> TRAMCUOI { get; set; }
    }
}
