//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMXE
    {
        public string MAXE { get; set; }
        public string SOXE { get; set; }
        public string LOAIXE { get; set; }
        public string MATAIXE { get; set; }
        public string SOGHE { get; set; }
    }
}
