//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCDKio
    {
        public int ID { get; set; }
        public string PHONG { get; set; }
        public string CounterName { get; set; }
        public string SQMS { get; set; }
        public string NEXT { get; set; }
        public Nullable<bool> CAM { get; set; }
        public string STT { get; set; }
        public string COUNTER { get; set; }
        public string TRANGTHAI { get; set; }
        public string STATUS { get; set; }
        public string MAU { get; set; }
        public string Loai { get; set; }
        public string DienGiai { get; set; }
    }
}
