//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusTicketEntities : DbContext
    {
        public BusTicketEntities()
            : base("name=BusTicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<Description_service> Description_services { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<DMHOADON> DMHOADONs { get; set; }
        public virtual DbSet<DMTAIXE> DMTAIXEs { get; set; }
        public virtual DbSet<DMTRAM> DMTRAMs { get; set; }
        public virtual DbSet<DMTUYEN> DMTUYENs { get; set; }
        public virtual DbSet<DMTUYENCHITIETTRAM> DMTUYENCHITIETTRAMs { get; set; }
        public virtual DbSet<DMXE> DMXEs { get; set; }
        public virtual DbSet<Docso> Docsoes { get; set; }
        public virtual DbSet<HIENTHI> HIENTHIs { get; set; }
        public virtual DbSet<LCD> LCDs { get; set; }
        public virtual DbSet<LCDKio> LCDKios { get; set; }
        public virtual DbSet<LOTRINHCHOXE> LOTRINHCHOXEs { get; set; }
        public virtual DbSet<PGD> PGDs { get; set; }
        public virtual DbSet<PHAN_LOAI_PGD> PHAN_LOAI_PGDs { get; set; }
    }
}
