//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string SQMS { get; set; }
        public Nullable<System.DateTime> GIOLAYSO { get; set; }
        public string dichvu1 { get; set; }
        public string GIAVE { get; set; }
        public string MATUYEN { get; set; }
        public string TENTUYEN { get; set; }
        public string MATRAMDAU { get; set; }
        public string MATRAMCUOI { get; set; }
        public string LOTRINH { get; set; }
        public string BienSoXe { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<bool> PHUCVU { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> Contro { get; set; }
        public Nullable<bool> Doc { get; set; }
        public Nullable<bool> DATCHO { get; set; }
        public Nullable<System.DateTime> GIO_GOC { get; set; }
        public string BINH_CHON { get; set; }
        public Nullable<System.DateTime> GIO_BINHCHON { get; set; }
        public string NGONNGU { get; set; }
        public string DIEMGIAODICH { get; set; }
        public string MANV { get; set; }
        public string QUAYCHUYEN { get; set; }
        public string QUAYTHAMCHIEU { get; set; }
        public string SODIENTHOAI { get; set; }
        public string QUAY { get; set; }
        public Nullable<System.DateTime> GIOPHUCVU { get; set; }
        public string MAXE { get; set; }
        public string MATAIXE { get; set; }
        public string MATRAM { get; set; }
        public string IDTUYEN { get; set; }
        public string KYHIEUVE { get; set; }
        public string MAUSO { get; set; }
        public string MATRAMGIUA { get; set; }
    }
}
