//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMHOADON
    {
        public string IDHOADON { get; set; }
        public string MAXE { get; set; }
        public string KYHIEUVE { get; set; }
        public string MAUSO { get; set; }
        public Nullable<int> TONGSOVEPHATHANH { get; set; }
        public Nullable<int> SOVEHIENTAI { get; set; }
        public Nullable<int> IDVE { get; set; }
    }
}
