//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMTAIXE
    {
        public string MATAIXE { get; set; }
        public string TENTAIXE { get; set; }
        public Nullable<int> TUOI { get; set; }
        public string GIOITINH { get; set; }
        public string BANGLAI { get; set; }
        public string SDT { get; set; }
        public string DIACHINOIO { get; set; }
        public string EMAIL { get; set; }
    }
}
