//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docso
    {
        public int id { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string SQMS { get; set; }
        public Nullable<System.DateTime> GIOLAYSO { get; set; }
        public string QUAY { get; set; }
        public Nullable<bool> Doc { get; set; }
        public string NGONNGU { get; set; }
        public string BIENKIEMSOAT { get; set; }
        public string TRONGTAI { get; set; }
        public string TENTAIXE { get; set; }
        public string MATHE { get; set; }
        public string SODIENTHOAI { get; set; }
        public string Giovao { get; set; }
        public string Giolayhang { get; set; }
        public string Giora { get; set; }
        public string PLANT { get; set; }
        public Nullable<bool> CHECKOUT { get; set; }
        public string PO { get; set; }
        public string GIAYPHEP { get; set; }
    }
}
