//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIENTHI
    {
        public int ID { get; set; }
        public string NGANHANG { get; set; }
        public string SQMS { get; set; }
        public string STT { get; set; }
        public string Dichvu { get; set; }
        public Nullable<bool> Check { get; set; }
    }
}
