//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHAN_LOAI_PGD
    {
        public int id { get; set; }
        public string MAKHUVUC { get; set; }
        public string TENKHUVUC { get; set; }
        public string Ghichu { get; set; }
    }
}
