//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingGP
    {
        public long IdTracking { get; set; }
        public string MaXe { get; set; }
        public string MaTuyen { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string DeviceId { get; set; }
        public Nullable<decimal> lng { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public string MaTram { get; set; }
    }
}
