//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiBusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        public string CopyRight { get; set; }
        public string LogoCopyRight { get; set; }
        public string CopyRightKey { get; set; }
        public Nullable<bool> ChedoInCSDL { get; set; }
        public Nullable<bool> ChedoInDefault { get; set; }
        public Nullable<bool> SetDefaultIn { get; set; }
        public Nullable<bool> MutiServices { get; set; }
        public Nullable<bool> TransferAuto { get; set; }
        public string TransferTime { get; set; }
        public string PGDCode { get; set; }
        public Nullable<bool> AutoNext { get; set; }
        public Nullable<bool> BackupSQLserver { get; set; }
        public string TieudeVN { get; set; }
        public string TieudeENG { get; set; }
        public string MST { get; set; }
        public string DT { get; set; }
        public string DCPRINT { get; set; }
        public string MAXE { get; set; }
        public string Luot { get; set; }
        public string Lastday { get; set; }
        public string TenCongTy { get; set; }
        public string DiaChi { get; set; }
    }
}
